[CustomKeymap/0]
# Key
Key=0
# Value
Value=XoaDauThanh

[CustomKeymap/1]
# Key
Key=1
# Value
Value=DauSac

[CustomKeymap/2]
# Key
Key=2
# Value
Value=DauHuyen

[CustomKeymap/3]
# Key
Key=3
# Value
Value=DauHoi

[CustomKeymap/4]
# Key
Key=4
# Value
Value=DauNga

[CustomKeymap/5]
# Key
Key=5
# Value
Value=DauNang

[CustomKeymap/6]
# Key
Key=6
# Value
Value=AEO_ÂÊÔ

[CustomKeymap/7]
# Key
Key=7
# Value
Value=UO_ƯƠ

[CustomKeymap/8]
# Key
Key=8
# Value
Value=A_Ă

[CustomKeymap/9]
# Key
Key=9
# Value
Value=D_Đ

