# Environment ------------------------------------------------------------------
[environment]
MOZ_ENABLE_WAYLAND = "1"
PROTON_ENABLE_WAYLAND = "1"
OZONE_PLATFORM = "wayland"
ELECTRON_OZONE_PLATFORM_HINT = "wayland"
SDL_VIDEODRIVER = "wayland"
SDL_VIDEO_WAYLAND_SCALE_TO_DISPLAY = "1"
GDK_BACKEND = "wayland,x11,*"
CLUTTER_BACKEND = "wayland"
_JAVA_AWT_WM_NONREPARENTING = "1"
NO_AT_BRIDGE = "1"
QT_QPA_PLATFORM = "wayland"
QT_QPA_PLATFORMTHEME = "qt6ct"
QT_WAYLAND_DISABLE_WINDOWDECORATION = "1"
