[main]
include=~/.config/foot/themes/rose-pine
# term=xterm-256color
term=foot
font=RecMonoSmCasual Nerd Font Propo:size=15
pad=17x17 center-when-maximized-and-fullscreen

[security]
osc52=enabled

[bell]
system=no

[scrollback]
lines=50000
indicator-position=none

[url]
launch=xdg-open ${url}

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes

[key-bindings]
scrollback-up-page=Shift+Up
scrollback-up-line=Control+Up
scrollback-down-page=Shift+Down
scrollback-down-line=Control+Down
scrollback-home=Alt+Shift+Up
scrollback-end=Alt+Shift+Down
clipboard-copy=Control+c
clipboard-paste=Control+v
search-start=Control+f
spawn-terminal=none
show-urls-launch=Control+q
show-urls-copy=Control+Shift+q
unicode-input=none

[search-bindings]
commit=Return
find-next=Down
find-prev=Up
