[main]
include=~/.config/foot/themes/rose-pine
# term=xterm-256color
term=foot
font=RecMonoCasual Nerd Font Propo:size=22
box-drawings-uses-font-glyphs=yes
pad=10x10 center-when-maximized-and-fullscreen
resize-by-cells=yes
resize-keep-grid=yes
word-delimiters=,│`|:"'()[]{}<>

[security]
osc52=enabled

[bell]
system=no

[scrollback]
lines=100000
indicator-position=none

[url]
launch=xdg-open ${url}

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes

[key-bindings]
scrollback-up-page=Shift+Up
scrollback-up-line=Control+Up
scrollback-down-page=Shift+Down
scrollback-down-line=Control+Down
clipboard-copy=Control+c
clipboard-paste=Control+v
search-start=Control+f
spawn-terminal=none
show-urls-launch=Control+u
show-urls-copy=Control+Shift+u
unicode-input=none

[search-bindings]
commit=Return
find-next=Down
find-prev=Up
