config_version = 13

[backdrop]
enabled = true

[bar]
order = [ "default" ]

    [bar.default]
    capsule = true
    capsule_opacity = 0.0
    capsule_padding = 4.0
    center = []
    concave_edge_corners = false
    enabled = true
    end = [ "tray", "battery", "network", "weather", "notifications", "clock" ]
    margin_ends = 0
    padding = 10
    radius = 0
    start = [ "control-center", "workspaces", "media" ]
    thickness = 26

[battery]
warning_threshold = 15

    [battery.device."/org/freedesktop/UPower/devices/headset_dev_A0_B0_BD_46_B9_ED"]
    warning_threshold = 7

[calendar]
enabled = true
refresh_minutes = 60

    [calendar.account.personal_google]
    color = "primary"
    name = "Lê Khang"
    type = "google"

[control_center]
sidebar = "full"
sidebar_section = "none"

    [[control_center.shortcuts]]
    type = "noctalia/screen_recorder:toggle"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "8bury/lid-guard:lid-guard-toggle"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
active_scale = 0.95000001415610313
background_opacity = 0.4999999888241291
cross_axis_padding = 2
enabled = true
icon_size = 41
inactive_opacity = 0.87999998033046722
inactive_scale = 0.95000001415610313
item_spacing = 0
magnification_scale = 1.4000000059604645
main_axis_padding = 3
margin_edge = 3
pinned = [
    "foot",
    "floorp",
    "com.discordapp.Discord",
    "equibop",
    "spotify-launcher",
    "zalo",
    "org.telegram.desktop",
    "app.fluxer.Fluxer",
    "org.vinegarhq.Sober",
    "org.vinegarhq.Vinegar",
    "steam",
    "org.polymc.PolyMC",
    "dev.zed.Zed",
    "code",
    "org.torproject.torbrowser-launcher",
    "blender-5.1",
    "us.zoom.Zoom",
    "com.obsproject.Studio",
    "com.cloudflare.WarpTaskbar",
    "winboat",
    "com.rustdesk.RustDesk",
    "io.podman_desktop.PodmanDesktop",
    "virt-manager",
    "dev.noctalia.Noctalia"
]
radius = 18
reserve_space = false
show_dots = true
show_instance_count = false
smart_auto_hide = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "suspend"
    enabled = true
    lock_before_suspend = false
    timeout = 1800.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
auto_locate = true
custom_schedule = true
sunrise = "06:00"
sunset = "18:00"

[lockscreen]
blur_intensity = 0.29999999329447746
fingerprint = false
tint_intensity = 0.44999998994171619

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000005", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 64
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 700.0
    cy = 792.5
    output = "eDP-1"
    placement_height = 875.0
    placement_width = 1400.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 700.0
    cy = 313.0
    output = "eDP-1"
    placement_height = 875.0
    placement_width = 1400.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        center_text = true
        color = "primary"
        format = "{:%I:%M %p\\n%A, %B %d}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 48.0
    box_width = 120.0
    cx = 824.0
    cy = 237.5
    output = "eDP-1"
    placement_height = 875.0
    placement_width = 1400.0
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        background = false

[nightlight]
enabled = true

[notification]
background_opacity = 0.87999998033046722
layer = "overlay"
scale = 0.90000000596046448

[osd]
background_opacity = 0.67999998480081558
position = "bottom_center"
position_vertical = "center_right"
scale = 0.90000000596046448

    [osd.kinds]
    keyboard_backlight = false
    keyboard_layout = false
    media = false

[plugin_settings."8bury/mini-docker"]
manager_position = "auto"

[plugin_settings."cleboost/anilist"]
client_id = "46918"
client_secret = "XbpQ3gVoS9zrUWCw8PbAgCw9TqkHQdZqIo7UQamG"
library_position = "auto"

[plugin_settings."cleboost/hotspot"]
panel_placement = "floating"
panel_position = "auto"
password = "!0968906049."
ssid = "inspiron14"

[plugin_settings."davemhammer/tailscale"]
manager_position = "auto"
ssh_user = "khang"

[plugin_settings."neyfua/obs-integration"]
checkout_dir = "~/Projects/OBS"
panel_position = "top_center"

[plugin_settings."nightwatch75/todo"]
panel_placement = "floating"

[plugin_settings."noctalia/notes"]
panel_position = "top_right"

[plugin_settings."noctalia/screen_recorder"]
restore_portal = true

[plugin_settings."tphilippot/git_companion"]
main_placement = "floating"

[plugins]
enabled = [
    "noctalia/screen_recorder",
    "nightwatch75/todo",
    "noctalia/wallhaven",
    "8bury/mini-docker",
    "yuuto/calculator",
    "8bury/lid-guard",
    "cleboost/hotspot",
    "noctalia/notes",
    "neyfua/obs-integration",
    "nightwatch75/dns-switcher",
    "davemhammer/tailscale",
    "cleboost/anilist",
    "tphilippot/git_companion"
]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
avatar_path = "/home/neyfua/Pictures/Pfps/HOPWJNka0AAdgHw_rose-pine.jpeg"
button_borders = false
card_borders = false
clipboard_auto_paste = "off"
clipboard_history_max_entries = 1000
clipboard_image_action_command = "swash"
date_format = "%A, %B %d %Y"
font_family = "SF Pro Display"
password_style = "random"
polkit_agent = true
screen_time_enabled = true
telemetry_enabled = true
time_format = "{:%-I:%M %p}"

    [shell.launcher]
    categories = false

    [shell.mpris]
    blacklist = [ "firefox", "Tor Browser" ]

    [shell.panel]
    borders = false
    clipboard_position = "auto"
    control_center_placement = "floating"
    floating_offset = 6
    launcher_position = "auto"
    list_item_background = true
    open_near_click_control_center = true
    session_placement = "floating"
    session_position = "center_left"
    wallpaper_placement = "floating"

    [shell.screenshot]
    confirm_region = true
    directory = "/home/neyfua/Pictures/Screenshots"
    remember_last_region = true

    [shell.session]
    grid = true
    grid_columns = 1
    show_shortcuts = false

        [[shell.session.actions]]
        action = "lock"
        countdown_seconds = 0.0
        enabled = false
        variant = "default"

        [[shell.session.actions]]
        action = "logout"
        countdown_seconds = 0.0
        enabled = true
        variant = "default"

        [[shell.session.actions]]
        action = "lock_and_suspend"
        countdown_seconds = 0.0
        enabled = true
        variant = "default"

        [[shell.session.actions]]
        action = "reboot"
        countdown_seconds = 0.0
        enabled = true
        variant = "default"

        [[shell.session.actions]]
        action = "shutdown"
        countdown_seconds = 0.0
        enabled = true
        variant = "destructive"

    [shell.shadow]
    direction = "center"

[system.monitor]
cpu_temp_activity_threshold = 80
cpu_temp_critical_threshold = 100
cpu_usage_activity_threshold = 80
cpu_usage_critical_threshold = 100
gpu_poll_seconds = 2
gpu_temp_activity_threshold = 80
gpu_temp_critical_threshold = 100
gpu_usage_activity_threshold = 80
gpu_usage_critical_threshold = 100
gpu_vram_activity_threshold = 80
gpu_vram_critical_threshold = 100
ram_pct_activity_threshold = 85
ram_pct_critical_threshold = 100
swap_pct_activity_threshold = 70
swap_pct_critical_threshold = 100

[theme]
builtin = "Rosé Pine"
mode = "dark"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper]
edge_smoothness = 0.24999999441206455
transition = [ "disc" ]
transition_duration = 2000

    [wallpaper.default]
    path = "/home/neyfua/Pictures/Wallpapers/the-maid.png"

    [wallpaper.last]
    path = "/home/neyfua/Pictures/Wallpapers/the-maid.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/neyfua/Pictures/Wallpapers/the-maid.png"

    [[wallpaper.favorite]]
    builtin_palette = "Rosé Pine"
    palette_source = "builtin"
    path = "/home/neyfua/Pictures/Wallpapers/motorcycle.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    builtin_palette = "Rosé Pine"
    palette_source = "builtin"
    path = "/home/neyfua/Pictures/Wallpapers/earrings.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    builtin_palette = "Rosé Pine"
    palette_source = "builtin"
    path = "/home/neyfua/Pictures/Wallpapers/violin.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    builtin_palette = "Rosé Pine"
    palette_source = "builtin"
    path = "/home/neyfua/Pictures/Wallpapers/chrome-angel(2).jpg"
    theme_mode = "dark"

[widget.active_window]
font_weight = 700

[widget.battery]
display_mode = "graphic"
show_label = false

[widget.clock]
color = "primary"
font_weight = 700
format = "{:%a, %b %d %Y  %-I:%M %p}"
tooltip_format = "{:%A, %B %-d %Y | %-I:%M:%S %p}"

[widget.control-center]
custom_image = "/home/neyfua/.local/share/noctalia/assets/images/distros/opensuse.svg"
custom_image_colorize = true

[widget.cpu]
show_value = false

[widget.media]
art_size = 18
hide_when_no_media = true
max_length = 800
min_length = 0
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.obs_integrate_2]
type = "neyfua/obs-integration:obs-integrate"

[widget.privacy]
hide_inactive = true

[widget.ram]
show_value = false

[widget.temp]
show_value = false

[widget.todo]
type = "nightwatch75/todo:todo"

[widget.tray]
drawer_columns = 5

[widget.volume]
mute_color = "outline"
show_label = false

[widget.weather]
show_condition = false

[widget.workspaces]
font_weight = 700
hide_when_empty = true
scale = 1.05
style = "focus_hint"