### Wayland default floats
		### Border pixel
		for_window [app_id="(^steam$|^org.kde.filelight$|^nemo$|^vesktop$)" title="(^(Sign in)(.*)$|^(Warning)(.*)$|^(.*)(Properties)$|^Choose an icon$|^vesktop$)"] border pixel 0

		### Floating
		for_window [app_id="(firefox|Calendar|Calculator|Power-statistics|Control-center|org.gnome.Weather|pavucontrol|psensor|mpv|xdg-desktop-portal-gtk|nemo|^org.telegram.desktop$)" title="(^Android Studio Setup Wizard$|^(.*)(Properties)$|^(Pushbullet)(.*)$|Library|About Mozilla Firefox|Firefox — Sharing Indicator|^(Picture-in-)(.*)$|^Media viewer$|^Open Files$)"] floating enable

		### Position center
		for_window [app_id="(pavucontrol|psensor|xdg-desktop-portal-gtk|org.telegram.desktop)" title="(^Media viewer$|^File Upload(.*)$|^Open Files$)"] move position center

		### Fullscreen
		for_window [app_id="^org.vinegarhq.Sober$"] fullscreen enable
		for_window [app_id="org.telegram.desktop" title="Media viewer"] fullscreen disable

		### Resize
		for_window [app_id="(pavucontrol|psensor)"] resize set 800 600
		for_window [app_id="firefox" title="(Library|^(Picture-in-)(.*)$)"] resize set 900 800
		for_window [app_id="xdg-desktop-portal-gtk" title="(^File Upload(.*)$|^Open Files$)"] resize set 1250 750
		for_window [app_id="mpv"] resize set 1452 820
		for_window [app_id="org.telegram.desktop" title="Media viewer"] resize set 1800 1000

		### Move to workspace
		for_window [app_id="(^code$|^dev.zed.Zed$|^jetbrains(.*)$|^antigravity$)"] move to workspace 1; workspace 1
		for_window [app_id="(^firefox$|^Tor Browser$)"] move to workspace 2; workspace 2
		for_window [app_id="(^vesktop$|^org.telegram.desktop$|^fluxer_app$)"] move to workspace 3; workspace 3
		for_window [app_id="(^org.vinegarhq.Sober$|^steam$|^com.heroicgameslauncher.hgl$|^PolyMC$|^(Minecraft)(.*)$)" title="(^Servers$|^Buy Robux$)"] move to workspace 4; workspace 4
		for_window [app_id="(^spotify$|^Spotify$)"] move to workspace 5; workspace 5
		for_window [app_id="^org.kde.kdenlive$" title="(^Kdenlive$|^(OBS)(.*)$)"] move to workspace 6; workspace 6

		# for_window [app_id="firefox" title="(^(Pushbullet)(.*)$|Library|About Mozilla Firefox|Firefox — Sharing Indicator)"] floating enable

### Windows
		default_border pixel 4
		smart_borders on

		corner_radius 12
		# gaps outer 12
		gaps inner 18

		shadows enable
		shadows_on_csd enable

		shadow_inactive_color #0000007F
		shadow_offset 0 0
		shadow_blur_radius 4
		shadow_color #0000007F

		titlebar_padding 6
		title_align center
