### Wayland default floats
		### Border pixel
		for_window [app_id="(^steam$|^org.kde.filelight$|^nemo$)" title="(^(Sign in)(.*)$|^(Warning)(.*)$|^(.*)(Properties)$|^Choose an icon$)"] border pixel 0
		for_window [app_id="vesktop" title="^vesktop$"] border pixel 0

		### Floating
		for_window [app_id="(Calendar|Calculator|Power-statistics|Control-center|psensor|xdg-desktop-portal-gtk|mpv|^org.(pulseaudio.pavucontrol|gnome.Weather)$|^(.*)(waytator)$)"] floating enable
		for_window [app_id="^firefox$" title="(^(Pushbullet)(.*)$|Library|About Mozilla Firefox|^(Firefox —)(.*)$|^(Picture-in-)(.*)$)"] floating enable
		for_window [app_id="nemo" title="^(.*)(Properties)$"] floating enable
		for_window [title="(Open Files|^(File Upload)(.*)$|Media viewer|^Android Studio Setup Wizard$)"] floating enable


		### Position center
		for_window [app_id="(^psensor$|^xdg-desktop-portal-gtk$|^org.(pulseaudio.pavucontrol|telegram.desktop)$|mpv|^dev.faetalize.waytator$|^firefox$|^vesktop$)"] move position center

		### Fullscreen
		for_window [app_id="org.telegram.desktop" title="Media viewer"] fullscreen disable

		### Resize
		for_window [app_id="(^org.pulseaudio.pavucontrol$|psensor|mpv)"] resize set 800 600
		for_window [app_id="firefox" title="(Library|^(Picture-in-)(.*)$)"] resize set 900 800
		for_window [title="(^File Upload(.*)$|^Open Files$)"] resize set 1100 600
		for_window [app_id="org.telegram.desktop" title="Media viewer"] resize set 1800 1000

		### Move to workspace
		for_window [app_id="(code|^(.*)(Zed)$|^jetbrains(.*)$|antigravity)"] move to workspace 1; workspace 1
		for_window [app_id="(firefox|^(Tor)(.*)$)"] move to workspace 2; workspace 2
		for_window [app_id="(vesktop|^org.telegram.desktop$|fluxer_app)"] move to workspace 3; workspace 3
		for_window [app_id="(spotify|Spotify)"] move to workspace 4; workspace 4
		for_window [app_id="^org.kde.kdenlive$" title="(^Kdenlive$|^(OBS)(.*)$)"] move to workspace 5; workspace 5

### Windows
		default_border pixel 4
		smart_borders on

		corner_radius 12
		# gaps outer 12
		gaps inner 18

		shadows enable
		shadows_on_csd enable

		shadow_inactive_color #0000007F
		shadow_offset 0 0
		shadow_blur_radius 4
		shadow_color #0000007F

		titlebar_padding 6
		title_align center
