### Rules
		## Border pixel
		for_window [app_id="steam|^(.*)filelight$|nemo" title="^(Sign in)(.*)$|^(Warning)(.*)$|^(.*)(Properties)$|Choose an icon"] border pixel 0
		for_window [app_id="vesktop" title="^vesktop$"] border pixel 0

		## Floating
		for_window [app_id="Calendar|Calculator|Power-statistics|Control-center|psensor|^xdg-desktop-portal-(.*)$|mpv|^org.(pulseaudio.pavucontrol|gnome.Weather)$|^(.*)(waytator)$"] floating enable
		for_window [app_id="^firefox$" title="^(Pushbullet)(.*)$|Library|About Mozilla Firefox|^(Firefox —)(.*)$|^(Picture-in-)(.*)$"] floating enable
		for_window [app_id="nemo" title="^(.*)(Properties)$"] floating enable
		for_window [title="Open Files|^(File Upload)(.*)$|Media viewer|^Android Studio Setup Wizard$|Noctalia Settings|Myrlyn-Password"] floating enable

		## Position center
		for_window [app_id="^psensor$|^xdg-desktop-portal-(.*)$|^org.(pulseaudio.pavucontrol|telegram)(.*)$|mpv|^(.*)waytator$|^firefox$|^vesktop$"] move position center

		## Fullscreen
		for_window [app_id="^(.*)telegram(.*)$" title="Media viewer"] fullscreen disable

		## Resize
		for_window [app_id="^(.*)pavucontrol$|psensor|mpv"] resize set 800 600
		for_window [app_id="firefox" title="Library|^(Picture-in-)(.*)$"] resize set 900 800
		for_window [title="^File Upload(.*)$|Open Files"] resize set 1100 600
		for_window [title="Noctalia Settings"] resize set 1150 750
		for_window [app_id="^(.*)telegram(.*)$" title="Media viewer"] resize set 1300 800

		## Move to workspace
		for_window [app_id="code|^(.*)(Zed)$|^jetbrains(.*)$|antigravity"] move to workspace 1; workspace 1
		for_window [app_id="firefox"] move to workspace 2; workspace 2
		for_window [app_id="vesktop|^(.*)telegram(.*)$|^fluxer(.*)$"] move to workspace 3; workspace 3
		for_window [app_id="spotify|Spotify"] move to workspace 4
		for_window [app_id="^(.*)kdenlive$" title="^Kdenlive$|^(OBS)(.*)$"] move to workspace 5; workspace 5

### Windows
		default_border pixel 3
		smart_borders on

		corner_radius 0
		# gaps outer 12
		gaps inner 14

		blur enable
		blur_xray disable
		blur_passes 2
		blur_noise 0.03
		blur_contrast 0.5
		blur_saturation 1.0

		shadows enable
		shadows_on_csd disable
		shadow_blur_radius 20
		shadow_color #0000003F
		shadow_offset 0 0
		shadow_inactive_color #0000003F

		titlebar_padding 6
		title_align center

		titlebar_separator enable
