[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "sysmon"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "weather"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "session"
